version: "2.3"

services:
  rust-mining-pool-api:
    build: .
    ports:
      - 9000:9000
    environment:
      DATABASE_URL: postgres://postgres:pass@postgres-docker/rust_mining_pool_api
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2
    hostname: postgres-docker
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: rust_mining_pool_api
    volumes:
      - ./migrations/2022-06-29-063214_rust_mining_pool_api/up.sql:/docker-entrypoint-initdb.d/up.sql
